sudo: required
services:
  - docker

before_install:
  - docker build -t shaharlazarovich/client-test -f ./client/Dockerfile.dev ./client
# the --coverage keyword is needed - otherwise npm test never exists
script:
  - docker run shaharlazarovich/client-test npm test -- --coverage

after_success:
  - docker build -t shaharlazarovich/multidocker-client ./client
  - docker build -t shaharlazarovich/multidocker-nginx ./nginx
  - docker build -t shaharlazarovich/multidocker-server ./server
  - docker build -t shaharlazarovich/multidocker-worker ./worker
#in order to push the images to docker hub, we need to login to the docker CLI
#we'll use 2 private environment variables we defined in travis CI
#the syntax is a linux equivalent so we could login automatically
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shaharlazarovich/multidocker-client
  - docker push shaharlazarovich/multidocker-nginx
  - docker push shaharlazarovich/multidocker-server
  - docker push shaharlazarovich/multidocker-worker
